project:
  type: website

website:
  title: "🎵 Sailing the Tides of Oceanus Folk"
  favicon: images/favicon.png
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: Overview
        href: poster.pdf
      - text: ShinyApp
        href: https://wshensi.shinyapps.io/shinyApp/
      - text: Prototype
        href: project_website/proj(Final).html
      - text: Team


format:
  html:
    theme: cosmo
    toc: true
    toc-location: right
    css: styles.css
