project:
  type: website

website:
  title: "ISSS608-VAA"
  navbar:
    background: "#2C3E50"
    foreground: "white"
    hover: "auto"
    dropdown-menu:
      background: "#34495E"
      foreground: "white"
      hover: "#2C3E50"
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Exercise 1"
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
          - text: "Exercise 2"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.html"
          - text: "Exercise 3 (part 1)"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.html"
          - text: "Exercise 3 (part 2)"
            href: "Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03.2.html"
          - text: "Exercise 4 (part 1)"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.1.html"
          - text: "Exercise 4 (part 2)"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.2.html"
          - text: "Exercise 4 (part 3)"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.3.html"
          - text: "Exercise 4 (part 4)"
            href: "Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex04.4.html"
          - text: "Exercise 5"
            href: "Hands-on_Ex/Hands-on_Ex05/Hands-on_Ex05.html"
          - text: "Exercise 6"
            href: "Hands-on_Ex/Hands-on_Ex06/Hands-on_Ex06.html"
          - text: "Exercise 8 (part 1)"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.html"
          - text: "Exercise 8 (part 2)"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.2.html"
          - text: "Exercise 8 (part 3)"
            href: "Hands-on_Ex/Hands-on_Ex08/Hands-on_Ex08.3.html"
          - text: "Exercise 9 (part 1 & 2)"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.html"
          - text: "Exercise 9 (part 3, 4 & 5)"
            href: "Hands-on_Ex/Hands-on_Ex09/Hands-on_Ex09.2.html"
          - text: "Exercise 10"
            href: "Hands-on_Ex/Hands-on_Ex10/Hands-on_Ex10.html"
      - text: "In-class Exercise"
        menu:
          - text: "Exercise 1"
            href: "In-class_Ex/In-class_Ex01/In-class_Ex01.html"
          - text: "Exercise 3"
            href: "In-class_Ex/In-class_Ex03/In-class_Ex03.html"
          - text: "Exercise 5"
            href: "In-class_Ex/In-class_Ex05/In-class_Ex05.html"
      - text: "Take-home Exercise"
        menu:
          - text: "Exercise 1 (Part 1)"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.html"
          - text: "Exercise 1 (Part 2)"
            href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01.2.html"
          - text: "Exercise 2"
            href: "Take-home_Ex/Take-home_Ex02/Take-home_Ex02.html"
          - text: "Exercise 3"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.html"
      - text: "ShinyApp"
        menu:
          - text: "Interactive Music Network Analysis"
            href: "Take-home_Ex/Take-home_Ex03/Take-home_Ex03.2.html"

    right:
      - href: index.qmd
        text: Home
      - about.qmd

  page-footer:
    left: "© 2025 ISSS608 - Visual Analytics"
    right: 
      - text: "Built with Quarto"

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    toc-depth: 2
    toc-title: "Page Contents"
    toc-location: left
    number-sections: true
    highlight-style: github

editor: visual
